### ISSUE TITLE
[RFC] Easier distribution development

### ISSUE THREAD

**Issue by xphere** [elcodi/bamboo-distribution#21]
Each change in bamboo-admin or bamboo-store settings needs to flow to distribution, and this is hard to mantain. We need to move to a workflow that eases this changes. Any ideas? Some comes to my mind:

1. Distribution loads configuration from admin and store
    `routing.yml` and `config.yml` in bamboo-admin and bamboo-store applications should be moved to `AdminCoreBundle` and `StoreCoreBundle` respectively. This makes the files accesible from bamboo-distribution to load them directly. No need to copy. Unfortunately, `security.yml` is still needed.

2. Join repositories and split on push
    The three repositories will share codebase and even the new BambooBundle can be added to this repository. Settings will also be shared by all. When pushing code, elcodibot can explode the result in three separated repositories, like we're doing with elcodi/elcodi.

3. 1 + 2 = 3
    Following both ideas at the same time, we can have automatic split repositories that can be cloned and used standalone. I haven't worked the ins and outs of this, but sounds good in my head, just saying.

Sure there are more and better, please share yours.

**Comment by mmoreram** [comment]
Done!
